#!/usr/bin/env bash
# Summary: Show the current Python version and its origin
#
# Shows the currently selected Python version and how it was
# selected. To obtain only the version string, use `pyenv
# version-name'.

set -e
[ -n "$PYENV_DEBUG" ] && set -x

exitcode=0
OLDIFS="$IFS"
IFS=: PYENV_VERSION_NAMES=($(pyenv-version-name)) || exitcode=$?
IFS="$OLDIFS"

for PYENV_VERSION_NAME in "${PYENV_VERSION_NAMES[@]}"; do
  if [ -d "${PYENV_ROOT}/versions/${PYENV_VERSION_NAME}" ]; then
    echo "user:$PYENV_VERSION_NAME (set by $(pyenv-version-origin))"
  else
    echo "root:$PYENV_VERSION_NAME (set by $(pyenv-version-origin))"
  fi
done

exit $exitcode
